### ISSUE TITLE
Bug: Permanent black loading screen after quitting to main menu

### ISSUE THREAD

**Issue by itsbudyn** [theLeaxx/JaLoader#11]
### Description
After saving and quitting the game to main menu, the game presents a language select screen. Upon selecting, the menu is permanently blocked behind a black loading screen. It seems to respond to mouse and keyboard presses judging by audio feedback, however the black screen still remains.
### Steps to reproduce
- Load save
- Play for any ammount of time
- Pause menu > Save & Quit > Accept
- Select language (which itself should be skipped I think)
### Expected result
Game returns to fully usable main menu.
### Actual result
Main menu is visually blocked by black loading screen. Can only blindly interact with keyboard.
### Screenshots/Video
[Video recording](https://streamable.com/bfbdla)
### Additional context
- The bug occurs regardless of "Skip Language Selection Screen" setting
- 100% reproduction rate on my end
- Failed to reproduce described bug on vanilla game
### Environment
- **OS**: Windows 11 22H2 (22621.2506)
- **Game version**: 1.105 (Steam)
- **JaLoader version**: 1.1.3
- **Additional mods**: None

**Comment by theLeaxx** [comment]
Fixed in [1.1.4](https://github.com/theLeaxx/JaLoader/releases/tag/1.1.4).
