### ISSUE TITLE
Bug: License plate style changes the colour of the car in a new game

### ISSUE THREAD

**Issue by itsbudyn** [theLeaxx/JaLoader#16]
### Description
Upon creating a new game, parts of the car take the colour of the license plate. It will be coloured the exact same way as the license plate (beige for on with default, red for diplomatic red, blue for diplomatic blue, and black for monochrome).
### Steps to reproduce
- Select a license plate style different than "off".
- Start new game (doesn't matter if tutorial is skipped or not).
### Expected result
The default colour of the car should remain unchanged.
### Actual result
Parts of the car are coloured after the numberplate.
### Screenshots/Video
[Video recording](https://streamable.com/g60ay0)
### Environment
- **OS**: Windows 11 23H2 (22631.2715)
- **Game version**: 1.105 (Steam)
- **JaLoader version**: 1.2.0
- **Additional mods**: None

**Comment by theLeaxx** [comment]
Fixed in [1.2.1](https://github.com/theLeaxx/JaLoader/releases/tag/1.2.1).
