### ISSUE TITLE
Allowing mod settings to read in text

### ISSUE THREAD

**Issue by Liebeg** [theLeaxx/JaLoader#34]
**Is your feature request related to a problem? Please describe.**
A mod has no way of getting a text from the user. Except via the console.

**Describe the solution you'd like**
My prefered solutotion would be adding the option to have a empty text field wich allows user inputs.

**Describe alternatives you've considered, if any**
I didn't consider any alternatives as this is the only sensful way of getting a a short text from the user.

**Additional context**

**Comment by theLeaxx** [comment]
Will be added in the next update, this month.

**Comment by theLeaxx** [comment]
![image](https://github.com/user-attachments/assets/e904ba9b-ef6e-4ec3-8416-f9c12a85934a)

Added, will release this week.

**Comment by Liebeg** [comment]
Looks great. Can there be added this invisible text that gets rid when typing? Like a password field that has the word password written in it till a letter is typed.

**Comment by theLeaxx** [comment]
> Looks great. Can there be added this invisible text that gets rid when typing? Like a password field that has the word password written in it till a letter is typed.

![image](https://github.com/user-attachments/assets/3a797a54-e30d-41e0-a18e-6a6c46374aa8)


Yes, that's added and customizable by the mod creator.
